# nmake makefile
#
# Tools used:
#  Compile::Watcom Resource Compiler
#  Compile::GNU C
#  Make: nmake or GNU make
all : cnrmenu.exe

cnrmenu.exe : cnrmenu.obj cnrmenu.res common.obj create.obj ctxtmenu.obj edit.obj populate.obj sort.obj cnrmenu.def
	gcc -Zomf cnrmenu.obj common.obj create.obj ctxtmenu.obj edit.obj populate.obj sort.obj cnrmenu.def -o cnrmenu.exe
	wrc cnrmenu.res

cnrmenu.obj : cnrmenu.c cnrmenu.h
	gcc -Wall -Zomf -c -O2 cnrmenu.c -o cnrmenu.obj

common.obj : common.c 
	gcc -Wall -Zomf -c -O2 common.c -o common.obj

create.obj : create.c 
	gcc -Wall -Zomf -c -O2 create.c -o create.obj

ctxtmenu.obj : ctxtmenu.c cnrmenu.h 
	gcc -Wall -Zomf -c -O2 ctxtmenu.c -o ctxtmenu.obj

edit.obj : edit.c 
	gcc -Wall -Zomf -c -O2 edit.c -o edit.obj

populate.obj : populate.c 
	gcc -Wall -Zomf -c -O2 populate.c -o populate.obj

sort.obj : sort.c
	gcc -Wall -Zomf -c -O2 sort.c -o sort.obj

cnrmenu.res : cnrmenu.rc 
	wrc -r cnrmenu.rc

clean :
	rm -rf *exe *res *obj *dll *map